---
- name: Build and push Docker image to ACR
  hosts: localhost
  connection: local
  become: true

  tasks:


    - name: Build Docker image
      docker_image:
        path: /app
        tag: latest
        buildargs:
          - ACR_USERNAME=EcomRegistr
          - ACR_PASSWORD=ydYcpFbaLyVmvcFBFxBxuTytQfTO/7Od7zXfEmW/eh+ACRBus9+4
          - ACR_NAME=EcomRegistr

    - name: Push Docker image to ACR
      docker_image:
        name: EcomRegistr.azurecr.io/ecomback:latest
        state: pushed

