---
- name: Build and push Docker image to ACR
  hosts: localhost
  vars:
    acr_name: EcomRegistr
    acr_login_server: "{{ acr_name }}.azurecr.io"
    acr_username: "EcomRegistr"
    acr_password: "ydYcpFbaLyVmvcFBFxBxuTytQfTO/7Od7zXfEmW/eh+ACRBus9+4"
    image_name: backend
    image_tag: latest
    dockerfile_path: ./Dockerfile
    context_path: /var/lib/jenkins/workspace/backend_Pipeline

  tasks:
    - name: Docker login to ACR
      community.docker.docker_login:
        registry_url: "{{ acr_login_server }}"
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"
        config_path: "/var/lib/jenkins/.docker/config.json"

    - name: Build the Docker image
      community.docker.docker_image:
        name: "{{ acr_login_server }}/{{ image_name }}:{{ image_tag }}"
        path: "{{ context_path }}"
        dockerfile: "{{ dockerfile_path }}"
        source: build

    - name: Push the Docker image to ACR
      community.docker.docker_image:
        name: "{{ acr_login_server }}/{{ image_name }}:{{ image_tag }}"
        source: local
        push: yes
