---
- name: Build and push Docker image to ACR
  hosts: localhost
  vars:
    acr_name: EcomRegistr
    acr_login_server: "{{ acr_name }}.azurecr.io"
    image_name: backecom
    image_tag: latest
    dockerfile_path: ./Dockerfile
    context_path: /var/lib/jenkins/workspace/backend_Pipeline
    acr_username: "EcomRegistr"
    acr_password: "ydYcpFbaLyVmvcFBFxBxuTytQfTO/7Od7zXfEmW/eh+ACRBus9+4"

  tasks:
    - name: Docker login to ACR
      docker_login:
        registry_url: "{{ acr_login_server }}"
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"

    - name: Build the Docker image
      docker_image:
        name: ecomregistr.azurecr.io/backend:latest 
        path: "{{ context_path }}"
        dockerfile: "{{ dockerfile_path }}"
        source: build
      vars:
        ansible_python_interpreter: usr/local/lib/python3.8

    # - name: Build the Docker image
    #   community.docker.docker_image:
    #       name: ecomregistr.azurecr.io/backend:latest
    #       path: /var/lib/jenkins/workspace/backend_Pipeline
    #       dockerfile: ./Dockerfile
    #       build: yes  # Ensure this parameter is included to indicate building from Dockerfile
    #       source: build
    #       state: present
    #       push: false
    #       force_tag: true
    #   become: yes
    #   become_user: root


    - name: Push the Docker image to ACR
      docker_image:
        name: ecomregistr.azurecr.io/backend:latest 
        source: local
        push: yes
      vars:
        ansible_python_interpreter: usr/local/lib/python3.8
