---
- name: Build and push Docker image to ACR
  hosts: localhost
  vars:
    acr_name: EcomRegistr  # Nom de votre Azure Container Registry
    acr_login_server: EcomRegistr.azurecr.io
    image_name: EcomRegistr.azurecr.io/backecom
    image_tag: latest
    dockerfile_path: ./Dockerfile
    context_path: ./app


    - name: Build the Docker image
      docker_image:
        name: "{{ acr_login_server }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        path: "{{ context_path }}"
        dockerfile: "{{ dockerfile_path }}"
        state: present

    - name: Push the Docker image to ACR
      docker_image:
        name: "{{ acr_login_server }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local

    # Exemple d'utilisation du résultat capturé
    - name: Print ACR login result
      debug:
        var: acr_login.stdout

    # Vous pouvez également vérifier si la connexion a réussi
    - name: Check ACR login status
      debug:
        msg: "ACR login succeeded"
      when: acr_login.rc == 0
