---
- name: Build and push Docker image to ACR
  hosts: All
  vars:
    acr_name: EcomRegistr  # Nom de votre Azure Container Registry
    acr_login_server: EcomRegistr.azurecr.io
    image_name: backecom
    image_tag: latest
    dockerfile_path: ./Dockerfile
    context_path: ./app

  tasks:
    - name: Log in to ACR
      shell: az acr login --name {{ acr_name }}
      register: acr_login
      ignore_errors: yes

    - name: Check ACR login status
      debug:
        msg: "ACR login succeeded"
      when: acr_login.rc == 0

    - name: Build the Docker image
      docker_image:
        build:
          path: "{{ context_path }}"
          dockerfile: "{{ dockerfile_path }}"
        name: "{{ acr_login_server }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        state: present

    - name: Push the Docker image to ACR
      docker_image:
        name: "{{ acr_login_server }}/{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: ansible
