---
- name: Build and push Docker image to ACR
  hosts: localhost
  vars:
    acr_login_server: "ecomregistr.azurecr.io"
    acr_username: "EcomRegistr"
    acr_password: "your_acr_password"
    docker_image_name: "backeom"
    workspace_path: "/var/lib/jenkins/workspace/backend_Pipeline"
    acr_name: EcomRegistr
    acr_login_server: "{{ acr_name }}.azurecr.io"
    dockerfile_path: ./Dockerfile
    acr_username: "EcomRegistr"
    acr_password: "ydYcpFbaLyVmvcFBFxBxuTytQfTO/7Od7zXfEmW/eh+ACRBus9+4"
---
- name: Build and push Docker image to ACR
  hosts: localhost
  tasks:
    - name: Docker login to ACR
      community.docker.docker_login:
        registry_url: "{{ acr_login_server }}"
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"
        reauthorize: yes

    - name: Build the Docker image
      community.docker.docker_image:
        name: "{{ acr_login_server }}/{{ docker_image_name }}"
        tag: latest
        path: "{{ workspace_path }}"
        dockerfile: Dockerfile
        state: present
        source: build

    - name: Push the Docker image to ACR
      community.docker.docker_image:
        name: "{{ acr_login_server }}/{{ docker_image_name }}"
        tag: latest
        push: yes
