---
- name: Deploy to AKS
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Set KUBECONFIG environment variable
      ansible.builtin.set_fact:
        KUBECONFIG: "{{ playbook_dir }}/kubeconfig"
      environment:
        ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3

    - name: Deploy backend
      kubernetes.core.k8s:
        kubeconfig: /var/lib/jenkins/.kube/config
        state: present
        definition: 
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: backend-deployment
            namespace: default


          spec:
            replicas: 2
            selector:
              matchLabels:
                app: backend
            template:
              metadata:
                labels:
                  app: backend
              spec:
                imagePullSecrets:
                - name: acr-auth
                containers:
                - name: backend
                  image: EcomRegistr.azurecr.io/backecom:latest
                  ports:
                  - containerPort: 8089
                  env:
                  - name: MYSQL_HOST
                    value: "mysql"  
                  - name: MYSQL_PORT
                    value: "3306"
                  - name: MYSQL_DATABASE
                    value: "mydatabase"
                  - name: MYSQL_USER
                    value: "mysqluser"
                  - name: MYSQL_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: mysql-secrets
                        key: MYSQL_PASSWORD


    - name: Deploy frontend
      kubernetes.core.k8s:
        kubeconfig: /var/lib/jenkins/.kube/config
        state: present
        definition: 
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: frontend-deployment
            namespace: default 

          spec:
            replicas: 2
            selector:
              matchLabels:
                app: frontend
            template:
              metadata:
                labels:
                  app: frontend
              spec:
                containers:
                - name: frontend
                  image: EcomRegistr.azurecr.io/frontecom:latest
                  ports:
                  - containerPort: 80  # NGINX usually listens on port 80
                imagePullSecrets:
                - name: acr-auth

- name: Deploy Services on Kubernetes
  hosts: localhost
  tasks:
    - name: Deploy backend-service
      kubernetes.core.k8s:
        kubeconfig: /var/lib/jenkins/.kube/config
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: backend-service
            namespace: default
          spec:
            selector:
              app: backend
            ports:
              - protocol: TCP
                port: 8089
                targetPort: 8089
            type: LoadBalancer    

    - name: Deploy frontend-service
      kubernetes.core.k8s:
        kubeconfig: /var/lib/jenkins/.kube/config
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: frontend-service
            namespace: default
          spec:
            selector:
              app: frontend
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
            type: LoadBalancer
