---
- name: Get AKS Credentials
  hosts: localhost
  gather_facts: no
  vars:
  environment:
    ansible_python_interpreter: /usr/local/bin/python3.8
  tasks:
    - name: Get AKS Cluster Info
      azure.azcollection.azure_rm_aks_info:
        resource_group: RFC_Ecom  # Remplacez par votre groupe de ressources AKS
        name: EcomCluster  # Remplacez par le nom de votre cluster AKS
      register: aks_info

    - debug:
        var: aks_info

    - name: Save AKS credentials to kubeconfig
      azure.azcollection.azure_rm_aks:
        resource_group: RFC_Ecom
        name: EcomCluster
        state: present
        register: aks_credentials

    - name: Write kubeconfig to file
      copy:
        content: "{{ aks_credentials.ansible_facts.azure_rm_aks.kube_config }}"
        dest: "{{ playbook_dir }}/kubeconfig"
        mode: '0600'
