---
- name: Fetch AKS kubeconfig from Terraform
  hosts: localhost
  tasks:
    - name: Get kubeconfig from Terraform output
      shell: /usr/bin/terraform output kube_config --query 'value' -raw
      register: kubeconfig

    - name: Set Kubernetes config for current session
      set_fact:
        kubeconfig_content: "{{ kubeconfig.stdout }}"

    - name: Write kubeconfig to file
      copy:
        content: "{{ kubeconfig_content }}"
        dest: "{{ ansible_env.HOME }}/.kube/config"
        mode: 0600
