---
- name: Get AKS Credentials
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  tasks:
    - name: Get AKS Cluster Info
      azure.azcollection.azure_rm_aks_info:
        resource_group: RFC_Ecom   
        name: EcomCluster        
      register: aks_info

    - debug:
        var: aks_info

    - name: Save AKS credentials to kubeconfig
      azure.azcollection.azure_rm_aks:
        resource_group: RFC_Ecom   
        name: EcomCluster          
        kube_config: yes
        state: present
      register: aks_credentials

    - name: Write kubeconfig to file
      copy:
        content: "{{ aks_credentials.azure_rm_aks.kube_config }}"
        dest: "{{ playbook_dir }}/kubeconfig"
        mode: '0600'

