---
- name: Get AKS Info
  hosts: localhost
  tasks:
    - name: Get AKS Cluster Info
      azure.azcollection.azure_rm_aks_info:
        resource_group: RFC_Ecom  # Remplacez par votre groupe de ressources AKS
        name: EcomCluster  # Remplacez par le nom de votre cluster AKS
      register: aks_info

    - debug:
        var: aks_info   
