---
- name: Fetch AKS kubeconfig from Terraform
  hosts: localhost
  tasks:
    - name: Get kubeconfig from Terraform output
      shell: /usr/bin/terraform output kube_config 
      register: kubeconfig
      changed_when: false


    - name: Set Kubernetes config for current session
      set_fact:
        kubeconfig_content: "{{ kubeconfig.stdout }}"

    - name: Create .kube directory if it does not exist
      file:
        path: /var/lib/jenkins/.kube
        state: directory
        mode: 0755

    - name: Write kubeconfig to file
      copy:
        content: "{{ kubeconfig_content }}"
        dest: "{{ ansible_env.HOME }}/.kube/config"
        mode: 0600
