---
- name: Get AKS Credentials
  hosts: localhost
  tasks:
    - name: Fetch AKS credentials
      command: az aks get-credentials --resource-group RFC_Ecom --name EcomCluster --file ./kubeconfig
      register: aks_credentials

    - debug:
        var: aks_credentials
