---
- name: Apply Kubernetes Ingress
  hosts: localhost
  tasks:
    - name: Apply Ingress Resource
      k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: myapp-ingress-RFC
            namespace: default
            annotations:
              nginx.ingress.kubernetes.io/rewrite-target: /
          spec:
            rules:
              - host: 135.236.137.80  # Replace with your actual domain or IP address
                http:
                  paths:
                    - path: /api
                      pathType: Prefix
                      backend:
                        service:
                          name: backend-service
                          port:
                            number: 8089
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: frontend-service
                          port:
                            number: 80
