apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress-rfc
spec:
  ingressClassName: azure-application-gateway
    annotations:
      appgw.ingress.kubernetes.io/ssl-redirect: "true"
      appgw.ingress.kubernetes.io/backend-protocol: "http"
  rules:
    - host: ecom.rfc.com
      http:
        paths:
          - path: /api
            pathType: Exact
            backend:
              service:
                name: backend-service
                port:
                  number: 8089
          - path: /
            pathType: Exact
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
