apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecomapp-ingress
  namespace: default
spec:
  rules:
  - host: ecom.rfc.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
