- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    kubeconfig_path: "/var/lib/jenkins/kubeconfig"
  tasks:
    - name: Set KUBECONFIG environment variable
      ansible.builtin.set_fact:
        KUBECONFIG: "{{ kubeconfig_path }}"
      environment:
        ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3

    - name: Deploy Ingress
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: my-app-ingress
            namespace: "default"
            annotations:
              kubernetes.io/ingress.class: "nginx"
              ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          spec:
            ingressClassName: nginx
            rules:
              - host: ecomrfc.dc2.cloudapp.xpressazure.com
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: frontend-service
                          port:
                            number: 80



