- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    kubeconfig_path: "/var/lib/jenkins/kubeconfig"
  tasks:
    - name: Set KUBECONFIG environment variable
      ansible.builtin.set_fact:
        KUBECONFIG: "{{ kubeconfig_path }}"
      environment:
        ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3
        

    - name: Deploy Ingress
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: my-app-ingress
            namespace: ingress-nginx
            annotations:
              kubernetes.io/ingress.class: "nginx"
          spec:
            rules:
            - host: ecom.rfc.com
              http:
                paths:
                  -backend:
                    service:
                      name: frontend-service
                      port:
                        number: 80

